import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(new URL('../assets/js/cloud-state.js',import.meta.url),'utf8'),ctx);const core=ctx.window.CLOUD_STATE;
const plain=v=>JSON.parse(JSON.stringify(v));
test('cloud snapshot omits notebook, typed briefs, and device preferences',()=>{assert.deepEqual(plain(core.snapshot({courses:{},notes:{secret:'private'},brief:'private',theme:'dark',focus:true})),{courses:{}});});
test('concurrent device changes preserve separate completed lessons',()=>{const base={courses:{cowork:{completed:{welcome:true}}}};const local={courses:{cowork:{completed:{welcome:true,steering:true}}}};const remote={courses:{cowork:{completed:{welcome:true,verify:true}}}};assert.deepEqual(plain(core.apply(remote,core.diff(base,local))).courses.cowork.completed,{welcome:true,verify:true,steering:true});});
test('first sync from two devices preserves newly created courses and lessons',()=>{const local={courses:{cowork:{completed:{welcome:true}}}};const remote={courses:{cowork:{completed:{verify:true}},code:{completed:{welcome:true}}}};assert.deepEqual(plain(core.apply(remote,core.diff({},local))),{courses:{cowork:{completed:{verify:true,welcome:true}},code:{completed:{welcome:true}}}});});
test('explicit undo and reset survive merging with remote progress',()=>{const base={courses:{cowork:{completed:{welcome:true,steering:true}}}};const local={courses:{cowork:{completed:{welcome:false}}}};const result=plain(core.apply(base,core.diff(base,local)));assert.deepEqual(result,local);});
test('guest import preserves account results and adds guest completions',()=>{const remote={courses:{cowork:{completed:{verify:true},quiz:{a:2}}},notes:{}};const local={courses:{cowork:{completed:{welcome:true},quiz:{a:0,b:1}}}};const result=plain(core.mergeImport(remote,local));assert.deepEqual(result.courses.cowork.completed,{verify:true,welcome:true});assert.deepEqual(result.courses.cowork.quiz,{a:2,b:1});});
test('sync rejects prototype pollution paths',()=>{assert.throws(()=>core.apply({},[{path:['__proto__','polluted'],value:true}]),/Invalid state path/);assert.equal({}.polluted,undefined);});
